id: etcd-keys

info:
  name: Etcd Keys
  author: sharath
  severity: info
  description: Scans for etcd keys
  tags: tech,k8s,kubernetes,devops,etcd

requests:
  - method: GET
    path:
      - "{{BaseURL}}/v2/keys/"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - '"node":'
          - '"key":'
        condition: and