id: netlify-takeover

info:
  name: netlify takeover detection
  author: 0xPrial,pdteam
  severity: high
  reference:
    - https://github.com/EdOverflow/can-i-take-over-xyz
  tags: takeover,netlify

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Not found - Request ID:"

      - type: word
        words:
          - "Netlify"
        part: header
