id: ssh-known-hosts

info:
  name: SSH Known Hosts
  author: geeknik
  severity: low
  reference:
    - https://datacadamia.com/ssh/known_hosts
  tags: config,exposure,ssh

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.ssh/known_hosts"
      - "{{BaseURL}}/.ssh/known_hosts.old"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "ssh-dss"
          - "ssh-ed25519"
          - "ssh-rsa"
          - "ecdsa-sha2-nistp256"
        condition: or

      - type: status
        status:
          - 200
