id: kube-api-services

info:
  name: Kube API Services
  author: sharath
  severity: info
  description: Scans for kube services
  tags: tech,k8s,kubernetes,devops,kube

requests:
  - method: GET
    path:
      - "{{BaseURL}}/api/v1/namespaces/default/services"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - '"ServiceList":'
          - '"items":'
        condition: and