id: kube-api-pods

info:
  name: Kube API Pods
  author: sharath
  severity: info
  description: Scans for kube pods
  tags: tech,k8s,kubernetes,devops,kube

requests:
  - method: GET
    path:
      - "{{BaseURL}}/api/v1/namespaces/default/pods"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - '"PodList":'
          - '"items":'
        condition: and