id: kube-api-namespaces

info:
  name: Kube API Namespaces
  author: sharath
  severity: info
  description: Scans for kube namespaces
  tags: tech,k8s,kubernetes,devops,kube

requests:
  - method: GET
    path:
      - "{{BaseURL}}/api/v1/namespaces"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - '"NamespaceList":'
          - '"items":'
        condition: and