id: kube-api-version

info:
  name: Kube API Version
  author: sharath,raesene
  severity: info
  description: Searches for exposed Kubernetes API servers which return version information unauthenticated
  tags: tech,k8s,kubernetes,devops,kube

requests:
  - method: GET
    path:
      - "{{BaseURL}}/version"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - '"major":'
          - '"minor":'
          - '"goVersion":'
        condition: and

    extractors:
      - type: json
        json:
          - ".gitVersion"