id: kubelet-healthz

info:
  name: Kubelet Healthz
  author: sharath
  severity: info
  description: Scans for kubelet healthz
  tags: tech,k8s,kubernetes,devops,kubelet

requests:
  - method: GET
    path:
      - "{{BaseURL}}/healthz"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: regex
        part: header
        regex:
          - "text/plain"

      - type: word
        part: body
        words:
          - "ok"

      - type: word
        part: header
        words:
          - "Kubernetes"