id: grandstream-device-configuration

info:
  name: Grandstream Device Configuration
  author: dhiyaneshDK
  severity: info
  metadata:
    shodan-query: http.title:"Grandstream Device Configuration"
  tags: iot

requests:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Grandstream Device Configuration</title>'

      - type: status
        status:
          - 200
